#[pgrx::pg_schema]
mod tests {
    use pgrx::*;

    use super::super::{BuilderNeighborCache, GraphNeighborStore, NeighborMergeMode};
    use crate::access_method::{
        graph::{
            neighbor_with_distance::{DistanceWithTieBreak, NeighborWithDistance},
            Graph, ListSearchResult,
        },
        labels::{LabelSet, LabelSetView, LabeledVector},
        meta_page::MetaPage,
        pg_vector::PgVector,
        plain::storage::PlainStorage,
        sbq::storage::SbqSpeedupStorage,
        stats::PruneNeighborStats,
        storage::{NodeDistanceMeasure, Storage},
    };
    use crate::util::{page::ReadablePage, tape::Tape, IndexPointer, ItemPointer};

    fn pointers(neighbors: &[NeighborWithDistance]) -> Vec<IndexPointer> {
        neighbors
            .iter()
            .map(NeighborWithDistance::get_index_pointer_to_neighbor)
            .collect()
    }

    fn page_and_wal_snapshot(
        index: &PgRelation,
        source: IndexPointer,
    ) -> (Vec<u8>, pg_sys::XLogRecPtr) {
        unsafe {
            let page = ReadablePage::read(index, source.block_number);
            // Include the page LSN and every node field. The backend-local WAL
            // position excludes unrelated WAL generated by concurrent backends.
            (
                std::slice::from_raw_parts((*page).cast::<u8>(), pg_sys::BLCKSZ as usize).to_vec(),
                pg_sys::XactLastRecEnd,
            )
        }
    }

    fn check_protocol<S: Storage>(storage: &S, index: &PgRelation, meta: &MetaPage) {
        let mut stats = PruneNeighborStats::default();
        let mut tape = unsafe { Tape::new(index, S::page_type()) };
        let labels = storage.get_has_labels().then(|| LabelSet::from(vec![1, 2]));
        let nodes: Vec<_> = (0..=meta.get_num_neighbors())
            .map(|i| {
                let node_labels = if i == 1 {
                    storage.get_has_labels().then(LabelSet::default)
                } else {
                    labels.clone()
                };
                storage.create_node(
                    &[i as f32 + 1.0, 1.0, 1.0],
                    node_labels,
                    ItemPointer::new(100 + i, 1),
                    meta,
                    &mut tape,
                    &mut stats,
                )
            })
            .collect();
        let source = nodes[0];
        assert!(nodes
            .iter()
            .all(|node| node.block_number == source.block_number));

        // Keep a distance measure alive across writes to its source page. It
        // must own its vector rather than retain a shared buffer lock.
        let measure = unsafe { storage.get_node_distance_measure(source, &mut stats) };
        let neighbors: Vec<_> = nodes[1..]
            .iter()
            .map(|&node| {
                NeighborWithDistance::new(
                    node,
                    DistanceWithTieBreak::new(
                        unsafe { measure.get_distance(node, &mut stats) },
                        source,
                        node,
                    ),
                    storage.get_labels(node, &mut stats),
                )
            })
            .collect();

        let before = page_and_wal_snapshot(index, source);
        let unchanged = stats.unchanged_writes;
        assert!(storage.try_set_neighbors_on_disk(source, &[], &[], &mut stats));
        assert_eq!(stats.unchanged_writes, unchanged + 1);
        assert_eq!(page_and_wal_snapshot(index, source), before);

        assert!(storage.try_set_neighbors_on_disk(source, &[], &neighbors, &mut stats));
        let full = storage.get_neighbors_with_distances_from_disk(source, &mut stats);
        assert_eq!(pointers(&full), nodes[1..]);
        let before = page_and_wal_snapshot(index, source);
        let unchanged = stats.unchanged_writes;
        // Only ordered pointers are persisted, not distances or neighbor labels.
        let same_pointers: Vec<_> = nodes[1..]
            .iter()
            .map(|&node| {
                NeighborWithDistance::new(
                    node,
                    DistanceWithTieBreak::new(999.0, source, node),
                    None,
                )
            })
            .collect();
        assert!(storage.try_set_neighbors_on_disk(source, &nodes[1..], &same_pointers, &mut stats));
        assert_eq!(stats.unchanged_writes, unchanged + 1);
        assert_eq!(page_and_wal_snapshot(index, source), before);

        let mut reversed = nodes[1..].to_vec();
        reversed.reverse();
        // A stale writer must retry even if its replacement already matches.
        assert!(!storage.try_set_neighbors_on_disk(source, &reversed, &neighbors, &mut stats));
        assert!(!storage.try_set_neighbors_on_disk(source, &[], &neighbors, &mut stats));
        assert!(!storage.try_set_neighbors_on_disk(source, &reversed, &[], &mut stats));
        assert!(!storage.try_set_neighbors_on_disk(source, &[], &[], &mut stats));
        assert_eq!(stats.unchanged_writes, unchanged + 1);
        assert_eq!(page_and_wal_snapshot(index, source), before);

        let refreshed = storage.get_neighbors_with_distances_from_disk(source, &mut stats);
        assert!(storage.try_set_neighbors_on_disk(
            source,
            &pointers(&refreshed),
            &neighbors,
            &mut stats,
        ));
        assert_eq!(stats.unchanged_writes, unchanged + 2);
        assert_eq!(page_and_wal_snapshot(index, source), before);

        // The same pointer set in a different order is a real write.
        let reversed_neighbors: Vec<_> = neighbors.iter().rev().cloned().collect();
        assert!(storage.try_set_neighbors_on_disk(
            source,
            &nodes[1..],
            &reversed_neighbors,
            &mut stats,
        ));
        assert_eq!(stats.unchanged_writes, unchanged + 2);
        assert_eq!(
            pointers(&storage.get_neighbors_with_distances_from_disk(source, &mut stats)),
            reversed
        );
        assert_ne!(page_and_wal_snapshot(index, source).1, before.1);
        assert!(storage.try_set_neighbors_on_disk(source, &reversed, &neighbors, &mut stats));
        assert_eq!(
            pointers(&storage.get_neighbors_with_distances_from_disk(source, &mut stats)),
            nodes[1..]
        );

        // Shrink a full adjacency: stale slots past the sentinel are not part
        // of either the snapshot or the subsequent comparison.
        assert!(storage.try_set_neighbors_on_disk(
            source,
            &nodes[1..],
            &neighbors[..1],
            &mut stats,
        ));
        assert_eq!(
            pointers(&storage.get_neighbors_with_distances_from_disk(source, &mut stats)),
            nodes[1..2]
        );
        let before = page_and_wal_snapshot(index, source);
        let unchanged = stats.unchanged_writes;
        assert!(storage.try_set_neighbors_on_disk(
            source,
            &nodes[1..2],
            &neighbors[..1],
            &mut stats,
        ));
        assert_eq!(stats.unchanged_writes, unchanged + 1);
        assert_eq!(page_and_wal_snapshot(index, source), before);
        assert!(storage.try_set_neighbors_on_disk(source, &nodes[1..2], &[], &mut stats));
        assert!(storage.try_set_neighbors_on_disk(source, &[], &neighbors[..1], &mut stats));

        let additions = vec![
            neighbors[0].clone(),
            neighbors[1].clone(),
            neighbors[1].clone(),
            NeighborWithDistance::new(
                source,
                DistanceWithTieBreak::new(0.0, source, source),
                labels.clone(),
            ),
        ];
        for _ in 0..2 {
            let (pruned, merged) = Graph::merge_neighbors_on_disk(
                storage,
                source,
                None,
                &additions,
                meta.get_max_alpha(),
                meta.get_num_neighbors() as usize,
                NeighborMergeMode::Disk,
                &mut stats,
            );
            assert!(!pruned);
            assert_eq!(pointers(&merged), nodes[1..3]);
            assert_eq!(
                merged[0].get_labels().map(LabelSetView::labels),
                neighbors[0].get_labels().map(LabelSetView::labels)
            );
        }

        let cache = BuilderNeighborCache::new(0.0, meta, 0);
        assert_eq!(
            cache.get_neighbors(source, storage, &mut stats),
            nodes[1..3]
        );
        assert_eq!(
            cache
                .neighbor_map
                .borrow_mut()
                .get(&source)
                .unwrap()
                .labels
                .as_ref()
                .map(LabelSetView::labels),
            labels.as_ref().map(LabelSetView::labels)
        );
        // Another writer publishes after the cache fill, before flushing it.
        assert!(storage.try_set_neighbors_on_disk(
            source,
            &nodes[1..3],
            &neighbors[..3],
            &mut stats,
        ));
        cache.flush_neighbor_cache(storage, &mut stats);
        assert_eq!(
            pointers(&storage.get_neighbors_with_distances_from_disk(source, &mut stats)),
            nodes[1..4]
        );

        // The eviction path must reconcile even when its cached list is empty.
        assert!(storage.try_set_neighbors_on_disk(source, &nodes[1..4], &[], &mut stats));
        assert!(cache.get_neighbors(source, storage, &mut stats).is_empty());
        assert!(storage.try_set_neighbors_on_disk(source, &[], &neighbors[..1], &mut stats));
        cache.get_neighbors(nodes[1], storage, &mut stats);
        assert_eq!(
            pointers(&storage.get_neighbors_with_distances_from_disk(source, &mut stats)),
            nodes[1..2]
        );
        assert_eq!(
            cache
                .neighbor_map
                .borrow_mut()
                .get(&nodes[1])
                .unwrap()
                .labels
                .as_ref()
                .map(LabelSetView::labels),
            neighbors[0].get_labels().map(LabelSetView::labels)
        );

        // Cache misses during both start-node creation and visiting can evict
        // nodes on the very same page. No readable node may span that lookup.
        assert!(storage.try_set_neighbors_on_disk(nodes[2], &[], &neighbors[..1], &mut stats));
        let mut store = GraphNeighborStore::Builder(cache);
        let query =
            storage.get_query_distance_measure(LabeledVector::new(PgVector::zeros(meta), None));
        let mut search = ListSearchResult::new(
            vec![nodes[2]],
            query,
            None,
            10,
            meta.get_num_neighbors(),
            &mut store,
            storage,
        );
        let visited = search.visit_closest(10).unwrap();
        storage.visit_lsn(&mut search, visited, &mut store, true);

        GraphNeighborStore::Disk.initialize_neighbors(storage, source, labels.clone(), &mut stats);
        assert_eq!(
            pointers(&storage.get_neighbors_with_distances_from_disk(source, &mut stats)),
            nodes[1..2]
        );
        store.initialize_neighbors(storage, nodes[3], labels.clone(), &mut stats);
        if let GraphNeighborStore::Builder(cache) = &store {
            let mut map = cache.neighbor_map.borrow_mut();
            let entry = map.get(&nodes[3]).unwrap();
            assert!(entry.neighbors.is_empty());
            assert_eq!(
                entry.labels.as_ref().map(LabelSetView::labels),
                labels.as_ref().map(LabelSetView::labels)
            );
        }
        assert_eq!(
            storage
                .get_labels(source, &mut stats)
                .as_ref()
                .map(LabelSetView::labels),
            labels.as_ref().map(LabelSetView::labels)
        );
        let current_measure = unsafe { storage.get_node_distance_measure(source, &mut stats) };
        assert_eq!(
            unsafe { current_measure.get_distance(nodes[1], &mut stats) },
            unsafe { measure.get_distance(nodes[1], &mut stats) }
        );

        // Traverse the disk path on this shared page and verify heap pointers
        // survived both successful writes and validated no-ops.
        let mut store = GraphNeighborStore::Disk;
        let query =
            storage.get_query_distance_measure(LabeledVector::new(PgVector::zeros(meta), None));
        let mut search = ListSearchResult::new(
            vec![source],
            query,
            None,
            10,
            meta.get_num_neighbors(),
            &mut store,
            storage,
        );
        let visited = search.visit_closest(10).unwrap();
        storage.visit_lsn(&mut search, visited, &mut store, true);
        assert_eq!(
            search.consume(storage),
            Some((ItemPointer::new(100, 1), source))
        );
        search.visit_closest(10).unwrap();
        assert_eq!(
            search.consume(storage),
            Some((ItemPointer::new(101, 1), nodes[1]))
        );
    }

    fn run_protocol(layout: &str, labeled: bool) -> spi::Result<()> {
        let label_column = if labeled { ", labels smallint[]" } else { "" };
        let label_attribute = if labeled { ", labels" } else { "" };
        Spi::run(&format!(
            "CREATE TABLE adjacency_test(embedding vector(3){label_column});
             CREATE INDEX adjacency_test_idx ON adjacency_test
             USING diskann(embedding vector_l2_ops{label_attribute})
             WITH (storage_layout = '{layout}', num_neighbors = 10);"
        ))?;
        let heap_oid =
            Spi::get_one::<pg_sys::Oid>("SELECT 'adjacency_test'::regclass::oid")?.unwrap();
        let index_oid =
            Spi::get_one::<pg_sys::Oid>("SELECT 'adjacency_test_idx'::regclass::oid")?.unwrap();
        let heap = unsafe { PgRelation::from_pg(pg_sys::RelationIdGetRelation(heap_oid)) };
        let index = unsafe { PgRelation::from_pg(pg_sys::RelationIdGetRelation(index_oid)) };
        let meta = MetaPage::fetch(&index);
        if layout == "plain" {
            let storage = PlainStorage::new_for_build(&index, &heap, &meta);
            check_protocol(&storage, &index, &meta);
        } else {
            let storage = unsafe {
                SbqSpeedupStorage::new_for_build(
                    &index,
                    &heap,
                    &meta,
                    &mut PruneNeighborStats::default(),
                )
            };
            check_protocol(&storage, &index, &meta);
        }
        Ok(())
    }

    #[pg_test]
    fn test_plain_adjacency_protocol() -> spi::Result<()> {
        run_protocol("plain", false)
    }

    #[pg_test]
    fn test_sbq_adjacency_protocol() -> spi::Result<()> {
        run_protocol("memory_optimized", false)
    }

    #[pg_test]
    fn test_labeled_sbq_adjacency_protocol() -> spi::Result<()> {
        run_protocol("memory_optimized", true)
    }
}
